### ISSUE TITLE
Async task for FoliaFlow generated an exception

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [Hynse/FoliaFlow#9] opened 2023-04-24 14:10 UTC
Hi, I think my server is update Folia last version but this err still have in my server
maybe...We should fix it right now ;)
--------------------------------------------
Logs:https://paste.ubuntu.com/p/gBVHDpd2vj/
--------------------------------------------
![HQ(M)@CWL)0Y2_1~VK3IQTR](https://user-images.githubusercontent.com/71379165/234022046-29e64e51-b95a-486c-8a8f-e39ad45fdf06.jpg)

**Comment by MidnightTale** [comment] 2023-04-24 14:26
i cant reproduce issues my didnt see any error 
this might fix can you try this https://github.com/Hynse/FoliaFlow/releases/tag/1.19.4-3

**Comment by xiaoyueyoqwq** [comment] 2023-04-24 14:30
> i cant reproduce issues my didnt see any error this might fix can you try this https://github.com/Hynse/FoliaFlow/releases/tag/1.19.4-3

Okay, I'd try it now

**Comment by xiaoyueyoqwq** [comment] 2023-04-24 14:40
> i cant reproduce issues my didnt see any error this might fix can you try this https://github.com/Hynse/FoliaFlow/releases/tag/1.19.4-3

No...I think it doesn't work
I tryed del world and del plugins but it didn't look useful...

**Comment by MidnightTale** [comment] 2023-04-24 14:42
Can i know list of plugins you using on that server have issue

**Comment by xiaoyueyoqwq** [comment] 2023-04-24 14:43
Hummm...I don't think the problem is with plugins, because I tried removing all plugins and only keeping your plugin, but it didn't work
![image](https://user-images.githubusercontent.com/71379165/234031498-68a22895-66ba-47d2-8ca4-8c4f56538bb8.png)

**Comment by xiaoyueyoqwq** [comment] 2023-04-24 14:45
> Can i know list of plugins you using on that server have issue

By the way, I use ZuluJDK 19
maybe this is problem?

**Comment by MidnightTale** [comment] 2023-04-24 18:26
this should be fix 100% and can you try build sand dupe on server do it work ?
https://github.com/Hynse/FoliaFlow/releases/tag/1.19.4-5

I think ZuluJDK 19 is not problem

**Comment by xiaoyueyoqwq** [comment] 2023-04-25 03:15
> this should be fix 100% and can you try build sand dupe on server do it work ?
> https://github.com/Hynse/FoliaFlow/releases/tag/1.19.4-5
> 
> I think ZuluJDK 19 is not problem

let me try it...

**Comment by xiaoyueyoqwq** [comment] 2023-04-25 03:43
> this should be fix 100% and can you try build sand dupe on server do it work ? https://github.com/Hynse/FoliaFlow/releases/tag/1.19.4-5
> 
> I think ZuluJDK 19 is not problem

No...I think it doesn't work
This is the full server log, maybe it can help you to find the bug?
--------------------------------------------------
https://paste.ubuntu.com/p/Vptd6zXQcf/
--------------------------------------------------

**Comment by MidnightTale** [comment] 2023-04-25 09:38
fixed on [version 1.6](https://github.com/Hynse/FoliaFlow/releases/tag/1.19.4-1.6)

**Closed as completed by MidnightTale** 2023-04-25 09:38 UTC
Labels: bug
